package client;

public class Client {
    public static void main(String[] args) {
        System.out.println("Menu:");
        System.out.println("1.Registry user");
        System.out.println("2.Login");
        System.out.println("For exit press \\q");
        System.out.println("Enter command number: 1\n");
        System.out.println("*** Registry user ***");
        System.out.println("Enter first name: Dan");
        System.out.println("Enter last name: Beehler");
        System.out.println("Enter date of birth (DD.MM.YYYY): 12.05.1989");
        System.out.println("Enter country: London");
        System.out.println("Enter sex (M/F): M");
        System.out.println("Enter password: qwerasdf1234");
        System.out.println("Repeat password: qwerasdf1234");
        System.out.println("*** Dan Beehler registered successfully *** \n");
        System.out.println("Menu:");
        System.out.println("1. Find user");
        System.out.println("2. List of users");
        System.out.println("3. Chat with user");
        System.out.println("4. Log out");
        System.out.println("Enter command number: 1 \n");
        System.out.println("*** Find user ***");
        System.out.println("Enter username: Kate");
        System.out.println("*** Kate was found *** \n");
        System.out.println("Menu:");
        System.out.println("1. Find user");
        System.out.println("2. List of users");
        System.out.println("3. Chat with user");
        System.out.println("4. Log out");
        System.out.println("Enter command number: 2 \n");
        System.out.println("*** List of users ***");
        System.out.println("| User name      | Status |");
        System.out.println("| Kate           | Online |");
        System.out.println("| Ira            | Offline|");
        System.out.println("*** End list of users *** \n");
        System.out.println("Menu:");
        System.out.println("1. Find user");
        System.out.println("2. List of users");
        System.out.println("3. Chat with user");
        System.out.println("4. Log out");
        System.out.println("Enter command number: 3 \n");
        System.out.println("*** Chat with user ***");
        System.out.println("Enter username: Kate");
        System.out.println("For exit press \\q");
        System.out.println("*** Chatting with Kate is started *** \n");
        System.out.println("Dan: Hello         10:16:53 12.01.2021");
        System.out.println("Dan: This is Dan   10:16:59 12.01.2021");
        System.out.println("Kate: Hello Dan!   10:17:59 12.01.2021");
        System.out.println("Dan: Bye!          10:18:59 12.01.2021");
        System.out.println("Dan: \\q");
        System.out.println("");
        System.out.println("Menu:");
        System.out.println("1. Find user");
        System.out.println("2. List of users");
        System.out.println("3. Chat with user");
        System.out.println("4. Log out");
        System.out.println("Enter command number: 4");
        System.out.println("*** Logout successfully *** \n");
        System.out.println("Menu:");
        System.out.println("1.Registry user");
        System.out.println("2.Login");
        System.out.println("For exit press \\q");
        System.out.println("\\q");
        System.out.println("*** Bye ***");
    }
}
